### ISSUE TITLE
Failed to fetch items

### ISSUE THREAD

**Issue by FAb7D** [omnivore-app/logseq-omnivore#205]
Recently it no longer works with the message "Failed to fetch items"

From console:
```
logseq-omnivore starting sync since: '
lsp://logseq.io/logs…dex-0a1bc9c3.js:234 Error: Unclosed section "datePublished" at 253
    at HS (index-0a1bc9c3.js:201:582)
    at mn.parse (index-0a1bc9c3.js:201:2380)
    at pn.parse (index-0a1bc9c3.js:203:1072)
    at rp (index-0a1bc9c3.js:222:1913)
    at _o (index-0a1bc9c3.js:234:443)
    at async Object.loadOmnivore (index-0a1bc9c3.js:237:263)
lsp://logseq.io/logs…dex-0a1bc9c3.js:224 reset loading state
```
and this
```
[frontend.handler.command-palette] {:command/register {:msg "Failed to register command. Command with same id already exist", :id :plugin.logseq-omnivore/omnivore-sync}, :line 91}
  | $cljs$core$apply_to_simple$cljs$0core$0IFn$0_invoke$0arity$06$$ | @ | main.js:8842
-- | -- | -- | --
  | $cljs$core$apply_to_simple$cljs$0core$0IFn$0_invoke$0arity$05$$ | @ | main.js:8739
  | $cljs$core$apply_to_simple$cljs$0core$0IFn$0_invoke$0arity$04$$ | @ | main.js:8736
  | $cljs$core$apply_to_simple$cljs$0core$0IFn$0_invoke$0arity$03$$ | @ | main.js:8733
  | $APP.$cljs$core$apply$$.$cljs$core$IFn$_invoke$arity$2$ | @ | main.js:101738
  | (anonymous) | @ | main.js:94607
  | $log_record_handler$$ | @ | main.js:36211
  | (anonymous) | @ | main.js:5438
  | $JSCompiler_StaticMethods_publish$$ | @ | main.js:5437
  | $goog$log$publishLogRecord$$ | @ | main.js:5478
  | $lambdaisland$glogi$log$cljs$0core$0IFn$0_invoke$0arity$04$$ | @ | main.js:36157
  | $frontend$handler$command_palette$register$$ | @ | main.js:91414
  | (anonymous) | @ | main.js:194338
  | R | @ | lsplugin.core.js:2
  | (anonymous) | @ | lsplugin.core.js:2
  | a.emit | @ | lsplugin.core.js:2
  | (anonymous) | @ | lsplugin.core.js:2
  | (anonymous) | @ | lsplugin.core.js:2
  | X.listener

</span></div>

```

**Comment by FAb7D** [comment]
I believe the problem is related to the closure of omnivore
