### ISSUE TITLE
Error when syncing highlights from PDFs

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/logseq-omnivore#45]
I have a feeling this is related to our parsing and sorting of patches. The patch data on a PDF is different from a web page, so this error was thrown:

```
Error: Invalid patch string: _<removed in case there was sensitive data
    at s.patch_fromText (index.bfcf26b1.js:2:89153)
    at c (index.bfcf26b1.js:2:91680)
    at index.bfcf26b1.js:2:166961
    at Array.sort (<anonymous>)
    at kr (index.bfcf26b1.js:2:166948)
    at async Object.loadOmnivore (index.bfcf26b1.js:2:169499)
 ```

**Comment by sywhb** [comment]
<img width="834" alt="Screenshot 2022-08-29 at 1 26 29 PM" src="https://user-images.githubusercontent.com/12963965/187128973-58a28507-e443-42be-8bde-81ff9cc02979.png">

Fixed in v1.8.1
